# CSI driver deployment placeholder (vendor specific)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-driver
  namespace: kube-system
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: csi-driver
    spec:
      containers:
        - name: csi-driver
          image: k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
